### ISSUE TITLE
Hi Leute wir haben einen Fehler

### ISSUE THREAD

**Issue by zentino** [int-lecture/repo-01#1]
curl -i -X GET -H "Accept:application/json" http://141.19.142.55:5000/messages/glatzo/1

Die Sequenznummer bleibt auf 0 und verändert sich nicht egal wieviele Nachrichten man schreibt.

**Comment by rlubaschewski** [comment]
die Sequenznummer wird zurückgesetzt sobald die Nachricht empfangen wurde.

**Comment by zentino** [comment]
Nee, so einfach läuft das nicht. Mfg Smits
