### ISSUE TITLE
Müssen neuöffnen.

### ISSUE THREAD

**Issue by incognito17** [int-lecture/repo-01#2]
Smits sagte müssen es neuöffnen:

--> curl -i -X GET -H "Accept:application/json" http://141.19.142.55:5000/messages/glatzo/1
     Die Sequenznummer bleibt auf 0 und verändert sich nicht egal wieviele Nachrichten man schreibt.

--> die Sequenznummer wird zurückgesetzt sobald die Nachricht empfangen wurde.

--> Nee, so einfach läuft das nicht. Mfg Smits

**Comment by ChristopherRotter** [comment]
Fehler wurde behoben.
