### ISSUE TITLE
Server gibt kein Response.

### ISSUE THREAD

**Issue by incognito17** [int-lecture/repo-01#3]
Wenn man mit PUT etwas sendet - sendet der Server kein Bestätigungsresponse, wie in der Aufgabenstellung und auch kein JSON-Bestätigungsobjekt:

"Sind die Daten korrekt formatiert, sendet der Server den Status 201 und ein Antwort-JSON mit der Sequenznummer und der Server-Zeit. Z.B.:

{
  "date": "2017-03-30T17:00:00Z",
  "sequence": 78
}"

**Comment by ChristopherRotter** [comment]
Fehler behoben. Das JSON-Objekt wurde korrekt erstellt, aber versehentlich nicht als String versendet.
