### ISSUE TITLE
Statuscode 400 wird nicht als Response zurückgegeben.

### ISSUE THREAD

**Issue by incognito17** [int-lecture/repo-01#4]
Wenn man eine Nachricht verschickt, die nicht korrekt formattiert wurde (z.B. Das Datum wurde weggelassen) - dann kommt ebenfalls kein Response vom Server zurück - so wie in der Aufgabe:

"Sind die Daten nicht korrekt formatiert, sendet der Server den Statuscode 400. Zusätzliche Felder werden aber ignoriert, damit man später das Protokoll einfacher erweitern kann."

**Comment by ChristopherRotter** [comment]
Funktioniert bei uns. Bitte beschreibt den Fehler und die Umstände der Entstehung genauer (curl-Befehl, etc.).

**Comment by incognito17** [comment]
Also wir haben das mit REST-Client getestet nicht mit Curl, diesen Rest-Client gab es als eine Erweiterung in Firefox (gibts auch in anderen Browsern viele Rest-Clients).

Und dort gibt er bei euch gar kein Response zurück - bei keiner Methode, also weder PUT noch GET 
(/send oder /messages/{user_id}).

Also immer keine Antwort von Server:
![001](https://cloud.githubusercontent.com/assets/22745342/25918264/1c4b58b0-35cb-11e7-9371-0f947479eb47.jpg)

![002](https://cloud.githubusercontent.com/assets/22745342/25918275/2a07b8a4-35cb-11e7-9c1f-bb556ce2c461.jpg)

Könnte man jetzt annhemen, dass es an dem Rest-Client selbst liegt, aber bei uns funktioniert es:

![003](https://cloud.githubusercontent.com/assets/22745342/25918311/45ccb9c2-35cb-11e7-84ad-c30e6c917b7e.jpg)

![004](https://cloud.githubusercontent.com/assets/22745342/25918317/4c493578-35cb-11e7-8963-146c42bfa523.jpg)


Mfg

**Comment by ChristopherRotter** [comment]
Danke für die Antwort. In unserer aktuellen Version funktioniert es, hab's mit dem "Advanced REST client" für Chrome getestet.
