### ISSUE TITLE
Versionen über Verzeichnisse

### ISSUE THREAD

**Issue by thomsmits** [int-lecture/repo-01#6]
git ist ein Versionsverwaltungssystem. Man bildet verschiedene Versionen einfach durch aufeinanderfolgende Commits oder durch Branches ab. Die Verwendung von Verzeichnissen entspricht nicht dieser Idee. Dies fällt mir insbesondere bei `public_html`, `public_html1_0` und `public_html_0.2` auf.

**Comment by rlubaschewski** [comment]
Überflüssige Verzeichnisse gelöscht, Code für die Website jetzt unter code/website zu finden
