### ISSUE TITLE
Zugriff auf userSequenceNumbers nicht threadsicher

### ISSUE THREAD

**Issue by thomsmits** [int-lecture/repo-01#7]
Die Methoden des JAX-RS-Services werden potentiell von mehreren Threads parallel aufgerufen. Deshalb sollte der Zugriff auf `userSequenceNumbers` entsprechend geschützt sein. Dasselbe gilt für die Datei-Operationen.

**Comment by ChristopherRotter** [comment]
Wir haben `userSequenceNumbers `jetzt als volatile markiert, die Methode `increaseUserSequence` als synchronized und alle  Dateioperationen auf dem Objekt `threadLock` synchronisiert. Reicht das?

**Comment by thomsmits** [comment]
Das `volatile` bringt nichts, der Rest passt aber.
